export const GAME = 'GAME'
export const GAME_SCREENS = 'GAME_SCREENS'
export const COUNT = 'COUNT'
export const GENRE = 'GENRE'
export const PLATFORM = 'PLATFORM'
export const GAMES = 'GAMES'
export const GENRES = 'GENRES'
export const PLATFORMS = 'PLATFORMS'